repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: pixi run --locked ruff check --force-exclude
        args: [--fix, --exit-non-zero-on-fix]
        language: system
        types_or: [python, pyi, jupyter]
        require_serial: true
      - id: ruff-format
        name: ruff format
        entry: pixi run --locked ruff format --force-exclude
        language: system
        types_or: [python, pyi, jupyter]
        require_serial: true
