site_name: fewspy documentation
site_url: https://d2hydro.github.io/fewspy
theme:
  name: "material"
  language: en
  logo: icons/logo/globe_only.png
  favicon: icons/logo/favicon.png
  highlightjs: true
  palette: 
    primary: blue

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/d2hydro/fewspy
nav:
    - Home: index.md
    - Installation: manuals/installation.md
    - Get started: manuals/get_started.ipynb
    - Contribute: manuals/contribute.md
    - Code Reference:
        - Api: reference/api.md
        - Wrappers: reference/wrappers.md
    - Tutorials:
        - Installation: tutorials/installation_tutorial.md
 