[workspace]
name = "fewspy"
version = "0.6.3"
description = "A Python API for the Deltares FEWS PI REST Web Service"
channels = ["conda-forge"]
platforms = ["win-64"]
readme = "README.md"
license = "MIT"
license-file = "LICENSE"

[tasks]
tests = "pytest --cov=fewspy --cov-report=term-missing ./tests"
pre-commit-install = "pre-commit install"

[dependencies]
aiohttp = "*"
geopandas = "*"
ipykernel = "*"
lxml = "*"
nest-asyncio = "*"
pandas = "*"
pre-commit = "*"
pyarrow = "*"
pydantic="*"
pytest = ">=9.0.3,<10"
pytest-black = "*"
pytest-cov = "*"
pytest-flakes = "*"
netCDF4 = "*"
twine = "*"
xarray="*"

[pypi-dependencies]
fewspy = { path = ".", editable = true }
build = "*"
pydantic = "*"
