name: fewspy

channels:
  - conda-forge
  - defaults

dependencies:
  - aiohttp
  - black
  - jupyter
  - pandas
  - geopandas
  - requests
  - pytest
  - pytest-cov
  - pytest-black
  - pytest-flakes
 