name: test

channels:
  - conda-forge
  - defaults

dependencies:
  - aiohttp
  - lxml
  - nest-asyncio
  - requests
  - pandas
  - geopandas
  - pip
  - pytest==7.4.3
  - pytest-cov
  - pytest-black
  - pytest-flakes